version: '3'

services:
  xardnode0:
    container_name: xardnode0
    image: "tendermint/xardnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-xard.log}
    volumes:
      - ./build:/xard:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  xardnode1:
    container_name: xardnode1
    image: "tendermint/xardnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-xard.log}
    volumes:
      - ./build:/xard:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  xardnode2:
    container_name: xardnode2
    image: "tendermint/xardnode"
    environment:
      - ID=2
      - LOG=${LOG:-xard.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/xard:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  xardnode3:
    container_name: xardnode3
    image: "tendermint/xardnode"
    environment:
      - ID=3
      - LOG=${LOG:-xard.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/xard:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
