---

- name: Copy binary
  copy:
    src: "{{XARCLI_BINARY}}"
    dest: /usr/bin/xarcli
    mode: 0755
  notify: restart xarcli

- name: Copy service
  template:
    src: xarcli.service.j2
    dest: /etc/systemd/system/xarcli.service
  notify: systemctl

