---

- name: Fetch genesis.json
  fetch: "src=/home/xard/.xard/config/genesis.json dest={{GENESISFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: xard

- name: Fetch config.toml
  fetch: "src=/home/xard/.xard/config/config.toml dest={{CONFIGFILE}} flat=yes"
  run_once: yes
  become: yes
  become_user: xard

